
FROM python:3.11-alpine AS runtime

ENV PYTHONUNBUFFERED=1 \
    POETRY_VERSION=0.0 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

RUN set -eux; \
    apk add --no-cache \
        ffmpeg \
        pandoc-cli \
        tectonic

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/app ./app

ENV CONVERTI_JOB_STORAGE_DIR=/app/storage/jobs

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
