
version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - CONVERTI_ALLOWED_ORIGINS=*
    volumes:
      - backend_storage:/app/storage
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_BASE_URL: /api
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  backend_storage:
